var = input("{}Digite algo: {}".format('\033[1;31m', '\033[m'))
print('{}O tipo primitivo desse valor é: {}'.format('\033[1;35m', type(var)))
print('Somente Espaços: {}'.format(var.isspace()))
print('Numerico: {}'.format(var.isnumeric()))
print('Alfabetico: {}'.format(var.isalpha()))
print('Alfanumerico: {}'.format(var.isalnum()))
print('Maiusculas: {}'.format(var.isupper()))
print('Minusculas: {}'.format(var.islower()))
print('Capitalizada: {}'.format(var.istitle()))
print('Decimal: {}'.format(var.isdecimal()))
print('Ascii: {}'.format(var.isascii()))
print('Digito: {}'.format(var.isdigit()))
print('Dentifier: {}'.format(var.isidentifier()))
print('Table {}'.format(var.isprintable()))

